In [1]:
import numpy as np

In [2]:
x = np.array([1,4,8])
x

array([1, 4, 8])

In [5]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(np.eye(8))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [9]:
print(np.empty((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
print(np.arange(1,3,2))

[1]


In [19]:
print(np.array([(4,3),(4,3)]))

[[4 3]
 [4 3]]


In [20]:
print(np.array([(4,3),(4,3)]).shape)

(2, 2)


In [21]:
print(np.arange(8))

[0 1 2 3 4 5 6 7]


In [22]:
print(np.arange(8).reshape(4,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [23]:
print(type(np.arange(8).reshape(4,2)))

<class 'numpy.ndarray'>


In [24]:
print(type(np.arange(8)))

<class 'numpy.ndarray'>


In [25]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
x = np.arange(8).reshape(4,2)

In [27]:
y = np.ones_like(x)

In [28]:
y

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [29]:
x = np.arange(200).reshape(40,5)

In [33]:
x=np.array([4,6,2,8])
np.median(x)

np.float64(5.0)

In [34]:
arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
